package view;

/**
 *
 * @author Felipe Umpierre
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form ProductView
     */
    public MainView() {
        initComponents();
        this.setSize(800, 800);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();
      jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
      jMenuItem1 = new javax.swing.JMenuItem();
      mainPane = new javax.swing.JDesktopPane();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu3 = new javax.swing.JMenu();
      table = new javax.swing.JMenu();
      tableNew = new javax.swing.JMenuItem();
      tableSearch = new javax.swing.JMenuItem();
      waiter = new javax.swing.JMenu();
      waiterNew = new javax.swing.JMenuItem();
      waiterSearch = new javax.swing.JMenuItem();
      product = new javax.swing.JMenu();
      productNew = new javax.swing.JMenuItem();
      productSearch = new javax.swing.JMenuItem();

      jMenu1.setText("jMenu1");

      jMenu2.setText("jMenu2");

      jRadioButtonMenuItem1.setSelected(true);
      jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

      jMenuItem1.setText("jMenuItem1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
      mainPane.setLayout(mainPaneLayout);
      mainPaneLayout.setHorizontalGroup(
         mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 618, Short.MAX_VALUE)
      );
      mainPaneLayout.setVerticalGroup(
         mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 431, Short.MAX_VALUE)
      );

      jMenu3.setText("Opções");

      table.setText("Mesas");

      tableNew.setText("Cadastrar");
      tableNew.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            tableNewActionPerformed(evt);
         }
      });
      table.add(tableNew);

      tableSearch.setText("Pesquisar");
      tableSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            tableSearchActionPerformed(evt);
         }
      });
      table.add(tableSearch);

      jMenu3.add(table);

      waiter.setText("Garçons");

      waiterNew.setText("Cadastrar");
      waiterNew.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            waiterNewActionPerformed(evt);
         }
      });
      waiter.add(waiterNew);

      waiterSearch.setText("Pesquisar");
      waiterSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            waiterSearchActionPerformed(evt);
         }
      });
      waiter.add(waiterSearch);

      jMenu3.add(waiter);

      product.setText("Produtos");

      productNew.setText("Cadastrar");
      productNew.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            productNewActionPerformed(evt);
         }
      });
      product.add(productNew);

      productSearch.setText("Pesquisar");
      productSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            productSearchActionPerformed(evt);
         }
      });
      product.add(productSearch);

      jMenu3.add(product);

      jMenuBar1.add(jMenu3);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainPane)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainPane)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void productNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNewActionPerformed

    private void productSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productSearchActionPerformed

    private void waiterNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterNewActionPerformed
        WaiterNew wn = new WaiterNew(0);
        mainPane.add(wn);
        
        wn.setVisible(true);
    }//GEN-LAST:event_waiterNewActionPerformed

    private void waiterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterSearchActionPerformed
        WaiterSearch ws = new WaiterSearch();
        mainPane.add(ws);
        
        ws.setVisible(true);
    }//GEN-LAST:event_waiterSearchActionPerformed

    private void tableNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNewActionPerformed
        TableNew tv = new TableNew(0);
        mainPane.add(tv);
        
        tv.setVisible(true);
    }//GEN-LAST:event_tableNewActionPerformed

    private void tableSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableSearchActionPerformed
        TableSearch ts = new TableSearch();
        mainPane.add(ts);
        
        ts.setVisible(true);
    }//GEN-LAST:event_tableSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
   private javax.swing.JDesktopPane mainPane;
   private javax.swing.JMenu product;
   private javax.swing.JMenuItem productNew;
   private javax.swing.JMenuItem productSearch;
   private javax.swing.JMenu table;
   private javax.swing.JMenuItem tableNew;
   private javax.swing.JMenuItem tableSearch;
   private javax.swing.JMenu waiter;
   private javax.swing.JMenuItem waiterNew;
   private javax.swing.JMenuItem waiterSearch;
   // End of variables declaration//GEN-END:variables
}
