/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import facade.FacadeOrders;
import facade.FacadeOrdersProduct;
import facade.FacadeProduct;
import facade.FacadeTable;
import facade.FacadeWaiter;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class OrderIndex extends InternalFrameHelper {

   protected FacadeTable facadeTable;

   /**
    * Creates new form Order
    */
   public OrderIndex() {
      facadeTable = new FacadeTable();

      initComponents();
      populateComboboxes();
   }

   public void populateComboboxes() {
      for (entity.Table t : facadeTable.listAll()) {
         tableComboBox.addItem(t.getNumber() + " - " + t.getCapacity() + " pessoa(s)");
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      tableComboBox = new javax.swing.JComboBox();
      jLabel3 = new javax.swing.JLabel();
      searchButton = new javax.swing.JButton();
      newOrder = new javax.swing.JButton();

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setText("Pedidos");

      jLabel2.setText("Mesa");

      tableComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma mesa" }));

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("Buscar informações de pedido por mesa");

      searchButton.setText("Pesquisar");
      searchButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchButtonActionPerformed(evt);
         }
      });

      newOrder.setText("Novo Pedido");
      newOrder.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            newOrderActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(newOrder))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(searchButton))
               .addComponent(tableComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(newOrder))
            .addGap(38, 38, 38)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel2)
            .addGap(1, 1, 1)
            .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
            .addComponent(searchButton)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void newOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderActionPerformed
      OrderNew on = new OrderNew();
      JDesktopPane desktopPane = getDesktopPane();
      desktopPane.add(on);

      on.setVisible(true);
      this.setVisible(false);
   }//GEN-LAST:event_newOrderActionPerformed

   private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
      String[] tableNumber = tableComboBox.getSelectedItem().toString().split(" - ");
      
      entity.Table t = facadeTable.listByNumber(Integer.parseInt(tableNumber[0]));
      
      OrderList o = new OrderList(t.getId());
      JDesktopPane desktopPane = getDesktopPane();
      desktopPane.add(o);

      o.setVisible(true);
      this.setVisible(false);
   }//GEN-LAST:event_searchButtonActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JButton newOrder;
   private javax.swing.JButton searchButton;
   private javax.swing.JComboBox tableComboBox;
   // End of variables declaration//GEN-END:variables
}
