/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import facade.FacadeProduct;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class ProductNew extends InternalFrameHelper {

   protected int id;

   /**
    * Creates new form TableView
    */
   public ProductNew(int id) {
      this.id = id;
      initComponents();

      if (this.id != 0) {
         FacadeProduct facadeProduct = new FacadeProduct();

         entity.Product p = facadeProduct.listByCode(this.id);

         if (p instanceof entity.Product) {
            this.name.setText(p.getName());
            this.code.setText(Integer.toString(p.getCode()));
            this.code.setEditable(false);
            this.price.setText(Double.toString(p.getPrice()));

            this.title.setText("Editando Produto");
         } else {
            message("Não foi encontrado nenhum produto com o código: " + this.id, "Produto não encontrado", JOptionPane.OK_OPTION);
         }
      }

      setClosable(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      name = new javax.swing.JTextField();
      code = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      insertButton = new javax.swing.JButton();
      cancelButton = new javax.swing.JButton();
      title = new javax.swing.JLabel();
      price = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setText("Nome do Produto");

      jLabel2.setText("Código");

      insertButton.setText("Salvar");
      insertButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            insertButtonActionPerformed(evt);
         }
      });

      cancelButton.setText("Cancelar");
      cancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
         }
      });

      title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      title.setText("Cadastro de Produto");

      jLabel4.setText("Preço");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addGroup(layout.createSequentialGroup()
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cancelButton)
                        .addComponent(jLabel2)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGap(18, 18, 18)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                           .addGap(0, 0, Short.MAX_VALUE)
                           .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel4)
                              .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGap(0, 0, Short.MAX_VALUE))))
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addGap(294, 294, 294))
                  .addComponent(name))
               .addComponent(title))
            .addContainerGap(13, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(39, 39, 39)
            .addComponent(title)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cancelButton))
            .addGap(24, 24, 24))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
      String name = this.name.getText();
      int code = Integer.parseInt(this.code.getText());
      Double price = Double.parseDouble(this.price.getText());

      FacadeProduct product = new FacadeProduct();

      boolean loadListPanel = false;

      if (this.id == 0) {
         entity.Product p = product.listByCode(code);

         if (p instanceof entity.Product) {
            message("Esse produto já foi cadastrado", "Produto existente", JOptionPane.ERROR_MESSAGE);
         } else {
            product.insert(code, name, price);
            message("Inserido com sucesso!", "Sucesso!", JOptionPane.ERROR_MESSAGE);

            loadListPanel = true;
         }
      } else {
         product.update(code, name, price);
         message("Atualizado com sucesso!", "Sucesso!", JOptionPane.ERROR_MESSAGE);

         loadListPanel = true;
      }

      if (loadListPanel) {
         ProductSearch ps = new ProductSearch();
         JDesktopPane desktopPane = getDesktopPane();
         desktopPane.add(ps);

         ps.setVisible(true);
         this.setVisible(false);
      }
   }//GEN-LAST:event_insertButtonActionPerformed

   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      ProductSearch ps = new ProductSearch();
      JDesktopPane desktopPane = getDesktopPane();
      desktopPane.add(ps);

      ps.setVisible(true);
      this.setVisible(false);
   }//GEN-LAST:event_cancelButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cancelButton;
   private javax.swing.JTextField code;
   private javax.swing.JButton insertButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JTextField name;
   private javax.swing.JTextField price;
   private javax.swing.JLabel title;
   // End of variables declaration//GEN-END:variables
}
